### ISSUE TITLE
Section numbering not working across blocks

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/support#10]
Reported by Thomas 

![OnYzsy4kUI](https://user-images.githubusercontent.com/1473646/142263207-17a5db28-b10f-4bb1-b0cb-3d06860c1027.gif)

 - 1.0.1 is a problem
 - 1.1 in block#2 should be 1.3

**Comment by rowanc1** [comment]
`1.1` is wrong, should be `1.3`, and then `1.3.1`

**Comment by stevejpurves** [comment]
possible way forward is to more tightly specify the article in `editor/styles/number.scss` so that other `hx` tags on the page don't mess up the numbering.

**Comment by stevejpurves** [comment]
@rowanc1 css bugs aside, which there are in ff apparently, this is not going to work for our case.
It would work for completely flat content as the `counter-reset` rules affect siblings and descendants, but not subsequent elements found on a depth-first traverse of the dom. 

https://codepen.io/stevejpurves/pen/WNZOByG

this reproduces the issue 👆 which does not occur if we remove the separating divs.

We need to move to a js based approach asap

**Comment by rowanc1** [comment]
This has been fixed up!
