### ISSUE TITLE
Working with Pandas Tables

### ISSUE THREAD

**Issue by rowanc1** [curvenote/support#2]
Pandas data frames can be converted to a text string that can be compiled as a table in latex using `df.to_latex()`. Similarly, this can be done with macros to convert excel tables (excel2latex) . Is there a way to use these generated text strings to make a table in curvenote or some other way to read in tables?

**Comment by rowanc1** [comment]
@stevejpurves I think this is now mostly working as export out to word and latex/pdf?

**Comment by stevejpurves** [comment]
it is but there is a remaining todo in pdf/latex

- [x] ensure that tables stay contained within page width in latex/pdf (put tables in an adjustbox is one possible solution)
