### ISSUE TITLE
Improve discoverability of download and authors editing

### ISSUE THREAD

**Issue by rowanc1** [curvenote/support#28]
> The location of the download button (in the "Authors" block doesn't feel intuitive to me. Instead, it would be nice if there was a "plus" sign here, and when you click on it, you could easily add additional authors. I'm also not entirely sure why, when clicking on the little 3 dots next to the "Share" button, the download option is greyed out, as to  me this feels like it would be the more logical place to download an article?

![image (22)](https://user-images.githubusercontent.com/913249/151037728-0efe0058-b659-4d2b-80f0-dfdfbb3b9d83.png)

**Comment by stevejpurves** [comment]
This has been addressed!

https://curvenote.com/oxa:9Kv3iYv0uCgaG0zl4WDZ/BbExDhwaRxvWSDNwsKmi.2
