### ISSUE TITLE
Enable changing the order of blocks in articles and notebooks

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/support#29]
> Are there any plans to make blocks easy to drag and move around, to change their order - similar to the functionalities in Jupyter notebook?

We want to provide 3 ways for a user to move a block
 1. drag and drop
 2. keyboard shortcuts  (mac: CMD+UP, CMD+DOWN ??, windows: CTRL+UP, CTRL+DOWN ???)
 3. Subtle UI controls

 2 & 3 are useful when there are large blocks or when DnD is not easy/possible

on the UI controls, we can use tooltips to provide hints for the keyboard shortcuts. Also we are sensitive to cluttering up the page in the editor, how are where could we add those? could they be added to the blue selected block handle on the LHS? will they stay visible for large blocks on scroll?

**Comment by stevejpurves** [comment]
@Yxwww this is the next one up - is this enough to go on? ☝🏼 can we start with a mockup / ideas about what that UI might look like.

**Comment by Yxwww** [comment]
Notion UX


https://user-images.githubusercontent.com/7460545/157492187-757a7928-52ed-4f4f-bf9a-418ad66467b6.mp4

**Comment by Yxwww** [comment]
Notion hotkey for moving blocks: `cmd` + `shift` + `up`/`down`. 

In normal text editors this combination is used to select the rest of the paragraphs from the cursor point ? 🤔

**Comment by rowanc1** [comment]
This has been deployed today!
