### ISSUE TITLE
Improve the "draft discarded" message.

### ISSUE THREAD

**Issue by rowanc1** [curvenote/support#3]
This should say something much less jarring, as we transition to moving to a better editing experience!

In the future we should seamlessly transition users from one version to the next and allow them to continue editing. Improving the popup is a good first step!

<img width="759" alt="temp draft discarded" src="https://user-images.githubusercontent.com/913249/139770527-d1d9f000-1b01-498b-9b75-d3269905510f.PNG">

**Comment by stevejpurves** [comment]
This has been addressed and is in production
