### ISSUE TITLE
Improve the styling of text/stream outputs in notebooks

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/support#41]
In a jupyter notebook, natively these will appear as simple black text with no background and rendered in a monospace font.
So doing something similar here would be good. We could also consider also enclosing it in a bounding box / block outline.

An example of a notebook with problematic output is here:
https://curvenote.com/@prisae/emg3d-as-solver-for-simpeg/simpeg-emg3d-inversion-automatic-grid

TODO:

 1. improve basic styling - align with juypter
 1. prevent unnecessary scrollbars

**Comment by Yxwww** [comment]
As discussed, this might be fixed by just switching the `<code />` to `<pre />`. It removes the unintended styles. And the text render better with monospace etc to preserve the original intend of these stream/text.

**Comment by stevejpurves** [comment]
this is now fixed!
