### ISSUE TITLE
Extension sign in panel for email/password is not working

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/support#46]
In the classic jupyter notebook interface, when logging in with email/password via the panel, it is not possible to type properly.
It appears that typing in the form triggers keyboard shortcuts in the notebook. Typing `d` can result in cells being deleted.

![6W0hYRn8J0](https://user-images.githubusercontent.com/1473646/164997284-7faed23b-86a1-4b37-a63c-cb478977ba2b.gif)

This does not happen in the `lab` interface.

**Comment by stevejpurves** [comment]
Note, when using the notebook you can log in via the extension popup

![2EMih7qeeh](https://user-images.githubusercontent.com/1473646/164997406-2daad7b3-81fe-46a8-b324-36817c0dde87.gif)

**Comment by rowanc1** [comment]
This is something that the keyboard shortcuts in the notebook are bound on the body, so there needs to be a stop event propagation on the inputs.

This is done in the comments as an example.

**Comment by stevejpurves** [comment]
fixed and soon to be deployed

![IVk3k8067S](https://user-images.githubusercontent.com/1473646/165305453-e1f94da5-8aeb-44f2-82f7-e780707e2c23.gif)
