### ISSUE TITLE
Add plain text / json / yaml option for embedded code blocks

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/support#49]
Add additional languages for prosemirror:
- [x] add options right after python
* text
* json
* yaml

![image (3)](https://user-images.githubusercontent.com/1473646/165951926-ef77c9e5-f5a6-46d4-8fa4-3eebca60fd73.png)

**Comment by rowanc1** [comment]
And yaml, and json!

**Comment by Yxwww** [comment]
PR: curvenote/editor/pull/135
