### ISSUE TITLE
Insert multiple citations after each other

### ISSUE THREAD

**Issue by AlexanderJuestel** [curvenote/support#73]
Hello, 

I am trying to add multiple citations after each other (see Screenshot) but have not found the shortcut to do so yet. I would like to have the following: (Author, 2000; Author et al., 2021;...)

![image](https://user-images.githubusercontent.com/45469915/186935243-3c755b3a-9b73-4478-8d50-1bffe2bc913a.png)

**Comment by stevejpurves** [comment]
@AlexanderJuestel you can do this at the moment by dragging one citation over the top of another to form a group, you can then add further citations by dragging into that group. I am assuming that the brackets shown here (...) were not manually placed but were added using by selecting the citation and using the `[]` button on the editor menu, doing so will form proper (`citep`) style citations. See below.
![DoxCT6yTLY](https://user-images.githubusercontent.com/1473646/187166247-0bd54d47-2513-43f5-9421-6aee06475ec3.gif)

**Comment by AlexanderJuestel** [comment]
@stevejpurves I can confirm that this solves my issue! Perfect! Thanks for that!
