### ISSUE TITLE
UTF-8 characters are replaced by - in document paths

### ISSUE THREAD

**Issue by huard** [curvenote/support#75]
In the path to a document, accented characters are replaced by `-`, see figure below for example. 
![image](https://user-images.githubusercontent.com/81219/199568772-c597f217-3377-4c14-a46a-1c324719b4b2.png)

**Comment by stevejpurves** [comment]
I see. We're stripping unicode / non-ascii characters from URL paths, but obviously could do better in terms of what those characters get replaced with. 

@huard  you may have already found this but the path can be updated / corrected in the Article block settings:

![7BRT8kgDO7](https://user-images.githubusercontent.com/1473646/199690851-5cc4306a-40c7-4a63-b14c-5222dfdc08b6.gif)

**Comment by huard** [comment]
Got it. Could change to a non-accented letter. 

Will let you decide whether to close this issue or not.

**Comment by rowanc1** [comment]
We have fixed this up locally (see linked PR above), it should be deployed early next week.

Thanks for the report!
