### ISSUE TITLE
Section titles are capitalized in table of content

### ISSUE THREAD

**Issue by huard** [curvenote/support#76]
In the table of content on the left hand side panel, section titles are automatically capitalized. In french, titles are not capitalized.

**Comment by stevejpurves** [comment]
@huard you're referring to the Groups shown here correct?

![image](https://user-images.githubusercontent.com/1473646/199691228-27ca6fcc-fa31-4c56-ad1e-42da2b9fca2e.png)

If I can also ask, the project that you are working on is that destined for a PDF, a website, or both?

**Comment by huard** [comment]
Yes, including subheadings as well. 
Most likely a PDF.

**Comment by rowanc1** [comment]
Hi @huard -- just removed these in the document outline and the capitalization in the navigation. The application should be deployed with these changes early next week.

Thanks for your report on this, and keep the requests coming!
