### ISSUE TITLE
Cannot edit document after saving

### ISSUE THREAD

**Issue by huard** [curvenote/support#77]
The web interface warned me of a loss of synchronization with the server. Although I hadn't saved, I could retrieve the draft I was working on by clicking Edit. However, I can't edit the document anymore, because.all keyboard strokes are ignored, except Space which is interpreted as "Page Down".

**Comment by huard** [comment]
Issue seems to have resolved itself on its own...

**Comment by stevejpurves** [comment]
@huard that is strange, we'll watch out for this happening again. Thanks for reporting this.
