### ISSUE TITLE
All figures from block disappeared 

### ISSUE THREAD

**Issue by huard** [curvenote/support#78]
I started editing a block and all figures within this block just vanished, leaving only the caption.

**Comment by rowanc1** [comment]
Does a refresh of the page restore the images?

**Comment by huard** [comment]
Yes it does !

**Comment by rowanc1** [comment]
Sorry about the scare.

We limit private image URLs to 12 hours and a unique, secure URL. There is a bug we need to properly track down that the app doesn't cache or properly request the new image URL for long-running editing sessions.

Thanks as always for the feedback.
