### ISSUE TITLE
Checkbox Options Unchecked after clicking BACK

### ISSUE THREAD

**Issue by emmaagcap** [curvenote/support#8]
If boxes are checked on the first page of Export Template Options, if you go back after having moved on to the next page, those boxes are no longer checked and will all have to be reselected. 
![Screen Recording 2021-10-25 at 12 57 53 PM](https://user-images.githubusercontent.com/89223352/138762330-06ed9aa4-5b09-4dfa-b8a6-589d781112e0.gif)

**Comment by emmaagcap** [comment]
Would also be great if these options stayed in place if you have to leave and go back to tag blocks/content. Maybe they stay until a new version of the article is saved?

**Comment by stevejpurves** [comment]
this is fixed!
